apiVersion: v1
kind: Namespace
metadata:
  name: flask-prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-prod
data:
  ENV: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: _IMAGE_
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: flask-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: flask-prod
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: flask-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: flask.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-svc
                port:
                  number: 80